gui:
    language: 'en'

os:
  edit: 'nvim {{filename}}'
  editAtLine: '{{editor}} +{{line}} -- {{filename}}'

# git:
#   paging:
#     colorArg: always
#     # pager: delta --paging=never --24-bit-color=never

